apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  backstage.io/kubernetes-id: health-106

resources:
#  - project.yaml
#  - rolebindings.yaml
  - health-106-deploy.yaml
  - health-106-service.yaml
  - health-106-route.yaml
