apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: health-106-production

images:
- digest: sha256:4f94c603c6f6041a9507c5579f8b1a524e200c4b422e3e43666a7e291e66352f
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: image-registry.openshift-image-registry.svc:5000/health-106-develop/health-106-record
